services:
  app:
    image: python:3.12
    container_name: app
    working_dir: /app
    restart: always
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: tail -f /dev/null
    entrypoint: >
      sh -c "pip install --upgrade pip &&
             pip install --upgrade setuptools &&
             tail -f /dev/null"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: contacts
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
